# Generated by Django 4.2.4 on 2023-09-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_Creacion_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_notas/'),
        ),
    ]
