"""elimine columna direccion

Revision ID: 73baa18b772a
Revises: 36dd89bf0fb3
Create Date: 2023-07-27 17:34:55.713587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73baa18b772a'
down_revision = '36dd89bf0fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
