"""creacion de la tabla mascotas

Revision ID: fbb96b4db0b4
Revises: 73baa18b772a
Create Date: 2023-07-27 19:22:27.452820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb96b4db0b4'
down_revision = '73baa18b772a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascota_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('Perro', 'Gato', 'Cuy', name='tipomascota'), nullable=False),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Helicoptero', 'Otro', name='sexomascota'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascota_model')
    # ### end Alembic commands ###
